spring:
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  jpa:
    show-sql: true
jwt:
  token:
    secret-key: "2048-game-key"
    expTime: 1800000
    issuer: "2048 game"