spring:
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true