spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(IM1MWaSCL2zDAVjipJY0ELt/WHQrzIpaGb8cDVamh7px8O+3O0BppOKgeph6YYFIJj3GwfNhetazqqmng6OA2IaucWTgJSOBwfsWLw8GcKsDA5/nSG3bIlSMwLaKA/Nm2ny+9JLvTzhYzR4cbbkqpnJX7pvN37g3QxCKoFnPmDk+RsbmoizCALYgVUJNVdU+QwZXY4qPuZs=)
    username: ENC(L56ictnQaHyLXVdCKr3VEXusPCSuItNC)
    password: ENC(KnMaatYAwsMzVtE2Te3uk10Z3BwZNQQh)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
jwt:
  token:
    secret-key: ENC(ncp6FR4Sg50kNvnSm+MZ8lWJ4jWZy876)
    expTime: ENC(IU7S5s6TbZRDtn+kdpj5Yw==)
    issuer: ENC(gshnN3M5dAh0OrQm0JmpOYiO+M+IMwi/)
logging:
  config: classpath:logback-prod.xml
sentry:
  dsn: ENC(FMK6bFLWfLNhD/VCmbDYw0Wjhi7MyOdJC98Zd84llM2ceysGq2gdrD5Ts+3lHoJqJrAHWPi0V4Ng9/Jt0nx9TAz4+aUuKKH4v0ieOehAUvpQPlTbvl79KA==)
  traces-sample-rate: 1.0